name: GLua Linter

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'lua/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'lua/**'
  workflow_dispatch:

jobs:
  run-linter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download latest GLuaFixer
        run: |
            $TAG=((Invoke-WebRequest "https://api.github.com/repos/FPtje/GLuaFixer/releases/latest").Content | ConvertFrom-Json).tag_name;
            Invoke-WebRequest "https://github.com/FPtje/GLuaFixer/releases/download/$TAG/glualint-$TAG-Windows.zip" -OutFile "glualint.zip"
        shell: powershell
      - name: Extract GLuaFixer
        run: Expand-Archive -Path "glualint.zip" -DestinationPath .
        shell: powershell
      - name: Lint GLua
        run: ./glualint.exe --config glualint.json .
