name: GLua Linter

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'lua/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'lua/**'
  workflow_dispatch:

jobs:
  run-linter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download latest GLuaFixer
        run: |
            $releases=((Invoke-WebRequest "https://api.github.com/repos/FPtje/GLuaFixer/releases").Content | ConvertFrom-Json);
            :find foreach($release in $releases) {
                foreach($asset in $release.assets) {
                $tag = $release.tag_name
                    if ($asset.name -ilike "*windows*.zip") {
                        $file = $asset.name
                        break find
                    }
                }
            };
            Invoke-WebRequest "https://github.com/FPtje/GLuaFixer/releases/download/$tag/$file" -OutFile "glualint.zip"
        shell: powershell
      - name: Extract GLuaFixer
        run: Expand-Archive -Path "glualint.zip" -DestinationPath .
        shell: powershell
      - name: Lint GLua
        run: ./glualint.exe --config glualint.json .
