name: "Create GitHub Release"

on:
  push:
    tags:
      - 'v**'

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Create zip"
        run: zip -r player_status_icons_${{ env.RELEASE_VERSION }}.zip lua

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip