name: "Create GitHub release"

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: "Create zip"
        run: |
          zip -r player_status_icons.zip lua

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip